use leptos::prelude::*;
use wasm_bindgen_futures::spawn_local;
use web_sys::window;
use std::time::Duration;

struct GoField {
    name: String,
    go_type: String,
    json_tag: String,
}

struct GoStruct {
    name: String,
    fields: Vec<GoField>,
}

fn to_pascal_case(s: &str) -> String {
    let mut result = String::new();
    let mut next_upper = true;
    for c in s.chars() {
        if c == '_' || c == '-' || c == ' ' || c == '.' {
            next_upper = true;
        } else if next_upper {
            result.push(c.to_ascii_uppercase());
            next_upper = false;
        } else {
            result.push(c);
        }
    }
    let cleaned: String = result.chars().filter(|c| c.is_alphanumeric()).collect();
    if cleaned.is_empty() {
        "Value".to_string()
    } else {
        cleaned
    }
}

fn generate_go_type(
    value: &serde_json::Value,
    field_name: &str,
    structs: &mut Vec<GoStruct>,
) -> String {
    match value {
        serde_json::Value::Null => "interface{}".to_string(),
        serde_json::Value::Bool(_) => "bool".to_string(),
        serde_json::Value::Number(num) => {
            if num.is_f64() {
                "float64".to_string()
            } else {
                "int".to_string()
            }
        }
        serde_json::Value::String(_) => "string".to_string(),
        serde_json::Value::Array(arr) => {
            if arr.is_empty() {
                "[]interface{}".to_string()
            } else {
                let elem_type = generate_go_type(&arr[0], field_name, structs);
                format!("[]{}", elem_type)
            }
        }
        serde_json::Value::Object(obj) => {
            let struct_name = to_pascal_case(field_name);
            let mut fields = Vec::new();
            
            // Sort keys to make the output deterministic
            let mut keys: Vec<&String> = obj.keys().collect();
            keys.sort();

            for key in keys {
                let val = &obj[key];
                let go_field_name = to_pascal_case(key);
                let sub_field_name = if struct_name.to_lowercase() == "autogenerated" {
                    to_pascal_case(key)
                } else {
                    format!("{}{}", struct_name, to_pascal_case(key))
                };
                
                let go_type = generate_go_type(val, &sub_field_name, structs);
                fields.push(GoField {
                    name: go_field_name,
                    go_type,
                    json_tag: format!("`json:\"{}\"`", key),
                });
            }

            let mut final_name = struct_name.clone();
            let mut counter = 1;
            while structs.iter().any(|s| s.name == final_name) {
                counter += 1;
                final_name = format!("{}{}", struct_name, counter);
            }

            structs.push(GoStruct {
                name: final_name.clone(),
                fields,
            });

            final_name
        }
    }
}

#[component]
pub fn JsonToGo() -> impl IntoView {
    let (input, set_input) = signal(String::new());
    let (root_name, set_root_name) = signal("AutoGenerated".to_string());
    let (copied, set_copied) = signal(false);

    let conversion_result = Memo::new(move |_| {
        let text = input.get();
        if text.trim().is_empty() {
            return Ok(String::new());
        }

        let parsed: serde_json::Value = match serde_json::from_str(&text) {
            Ok(val) => val,
            Err(e) => return Err(format!("Invalid JSON: {}", e)),
        };

        let mut structs = Vec::new();
        let name = if root_name.get().trim().is_empty() {
            "AutoGenerated".to_string()
        } else {
            root_name.get()
        };

        let root_type = generate_go_type(&parsed, &name, &mut structs);

        if structs.is_empty() {
            // Not an object or array of objects, just a primitive value
            return Ok(format!("// Root value type\ntype {} {}\n", name, root_type));
        }

        let mut output = String::new();
        output.push_str("// Auto-generated Go structs representing the JSON schema\n\n");
        for s in structs.iter().rev() {
            output.push_str(&format!("type {} struct {{\n", s.name));
            let max_name_len = s.fields.iter().map(|f| f.name.len()).max().unwrap_or(0);
            let max_type_len = s.fields.iter().map(|f| f.go_type.len()).max().unwrap_or(0);
            for f in &s.fields {
                output.push_str(&format!(
                    "\t{:<width_name$} {:<width_type$} {}\n",
                    f.name,
                    f.go_type,
                    f.json_tag,
                    width_name = max_name_len,
                    width_type = max_type_len
                ));
            }
            output.push_str("}\n\n");
        }

        Ok(output)
    });

    let output_text = Memo::new(move |_| {
        match conversion_result.get() {
            Ok(val) => val,
            Err(_) => String::new(),
        }
    });

    let error_msg = Memo::new(move |_| {
        match conversion_result.get() {
            Err(e) => Some(e),
            Ok(_) => None,
        }
    });

    let handle_copy = move |_| {
        let text = output_text.get();
        if text.is_empty() {
            return;
        }

        if let Some(win) = window() {
            let nav = win.navigator();
            let clipboard = nav.clipboard();
            let promise = clipboard.write_text(&text);
            
            spawn_local(async move {
                let result = wasm_bindgen_futures::JsFuture::from(promise).await;
                if result.is_ok() {
                    set_copied.set(true);
                    set_timeout(move || {
                        set_copied.set(false);
                    }, Duration::from_millis(1500));
                }
            });
        }
    };

    let handle_clear = move |_| {
        set_input.set(String::new());
    };

    let load_sample = move |_| {
        let sample = r#"{
  "id": 1024,
  "name": "Widget Pack",
  "active": true,
  "price": 29.99,
  "tags": ["utility", "rust", "wasm"],
  "dimensions": {
    "width": 12.5,
    "height": 8.0,
    "depth": 5.0
  },
  "manufacturer": {
    "name": "ACME Corp",
    "location": {
      "city": "Boston",
      "country": "USA"
    }
  }
}"#;
        set_input.set(sample.to_string());
    };

    view! {
        <div class="space-y-6">
            // Header
            <div>
                <h1 class="text-3xl font-bold tracking-tight text-slate-900 dark:text-white">"JSON to Go Struct"</h1>
                <p class="mt-1 text-slate-500 dark:text-slate-400 text-sm">"Convert JSON objects into fully typed, nested Go structs instantly."</p>
            </div>

            // Card panel
            <div class="bg-white dark:bg-slate-900 rounded-xl border border-slate-200 dark:border-slate-800 shadow-xs p-6 space-y-6">
                // Config
                <div class="flex flex-col sm:flex-row sm:items-center gap-4">
                    <div class="flex flex-col space-y-1.5 flex-1 max-w-sm">
                        <label class="text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400">"Root Struct Name"</label>
                        <input
                            type="text"
                            placeholder="AutoGenerated"
                            prop:value=root_name
                            on:input=move |ev| set_root_name.set(event_target_value(&ev))
                            class="px-3 py-2 bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 rounded-lg text-sm text-slate-900 dark:text-white focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500 outline-none transition-all"
                        />
                    </div>
                    <div class="flex items-end h-full pt-6">
                        <button
                            on:click=load_sample
                            class="px-4 py-2 border border-dashed border-slate-200 dark:border-slate-800 hover:border-indigo-500 dark:hover:border-indigo-500 text-indigo-600 dark:text-indigo-400 font-semibold rounded-lg text-sm transition duration-200"
                        >
                            "Load Sample JSON"
                        </button>
                    </div>
                </div>

                // Inputs
                <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
                    <div class="flex flex-col space-y-2">
                        <label class="text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400">"JSON Input"</label>
                        <textarea
                            rows="12"
                            placeholder="Paste JSON here..."
                            prop:value=input
                            on:input=move |ev| set_input.set(event_target_value(&ev))
                            class="w-full p-4 rounded-lg bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 font-mono text-xs focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500 outline-none resize-y transition-all custom-scrollbar"
                        />
                    </div>

                    <div class="flex flex-col space-y-2">
                        <label class="text-xs font-bold uppercase tracking-wider text-slate-500 dark:text-slate-400">"Go Struct Output"</label>
                        <textarea
                            rows="12"
                            readonly=true
                            placeholder="Go structs will appear here..."
                            prop:value=output_text
                            class="w-full p-4 rounded-lg bg-slate-50 dark:bg-slate-950 border border-slate-200 dark:border-slate-800 font-mono text-xs focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500 outline-none resize-y transition-all custom-scrollbar"
                        />
                    </div>
                </div>

                // Error
                {move || error_msg.get().map(|err| {
                    view! {
                        <div class="flex items-start space-x-3 p-4 bg-rose-50 dark:bg-rose-950/20 border border-rose-200 dark:border-rose-800/40 rounded-lg text-rose-800 dark:text-rose-400 transition-all duration-300">
                            <svg class="w-5 h-5 mt-0.5 flex-shrink-0" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24">
                                <path stroke-linecap="round" stroke-linejoin="round" d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
                            </svg>
                            <div class="text-sm font-medium">
                                {err}
                            </div>
                        </div>
                    }
                })}

                // Actions
                <div class="flex items-center justify-between border-t border-slate-200 dark:border-slate-800 pt-5">
                    <button
                        on:click=handle_clear
                        class="px-4 py-2 border border-slate-200 dark:border-slate-800 hover:bg-slate-100 dark:hover:bg-slate-800 text-slate-700 dark:text-slate-300 font-semibold rounded-lg text-sm transition duration-200"
                    >
                        "Clear"
                    </button>

                    <button
                        on:click=handle_copy
                        disabled=move || output_text.get().is_empty()
                        class=move || {
                            let disabled = output_text.get().is_empty();
                            let is_copied = copied.get();
                            format!(
                                "flex items-center space-x-2 px-5 py-2 font-semibold rounded-lg text-sm transition-all duration-200 {}",
                                if disabled {
                                    "bg-slate-100 dark:bg-slate-800 text-slate-400 dark:text-slate-600 cursor-not-allowed"
                                } else if is_copied {
                                    "bg-emerald-600 hover:bg-emerald-700 text-white shadow-xs"
                                } else {
                                    "bg-indigo-600 hover:bg-indigo-700 text-white shadow-xs hover:shadow-indigo-500/10"
                                }
                            )
                        }
                    >
                        {move || if copied.get() {
                            view! {
                                <svg class="w-4 h-4" fill="none" stroke="currentColor" stroke-width="2.5" viewBox="0 0 24 24">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="M5 13l4 4L19 7" />
                                </svg>
                                <span>"Copied!"</span>
                            }.into_any()
                        } else {
                            view! {
                                <svg class="w-4 h-4" fill="none" stroke="currentColor" stroke-width="2" viewBox="0 0 24 24">
                                    <path stroke-linecap="round" stroke-linejoin="round" d="M8 5H6a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2v-1M8 5a2 2 0 002 2h2a2 2 0 002-2M8 5a2 2 0 002 2h2a2 2 0 002-2m0 0h2a2 2 0 012 2v3m2 4H10m0 0l3-3m-3 3l3 3" />
                                </svg>
                                <span>"Copy Result"</span>
                            }.into_any()
                        }}
                    </button>
                </div>
            </div>
        </div>
    }
}
